name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build with Buildozer
        uses: n0nci/kivy_buildozer@main
        with:
          work-dir: .
          buildozer-cmd: buildozer android debug
